repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        args:
          - src
          - tests
          - --select I  # Only run the "I" category to auto sort imports
          - --fix
          - --exit-non-zero-on-fix
#  - repo: https://github.com/python/black.git
#    rev: 22.6.0
#    hooks:
#      - id: black
#        language_version: python3.11
#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.0.278
#    hooks:
#      - id: ruff
#        args:
#          - src
#          - tests
